// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsMujVJ0CIIhgWaS6hvt_WZ6F5LCjOAbQ',
    appId: '1:428608858205:web:8102e558eede37d98445b4',
    messagingSenderId: '428608858205',
    projectId: 'govt-billing-app',
    authDomain: 'govt-billing-app.firebaseapp.com',
    storageBucket: 'govt-billing-app.appspot.com',
    measurementId: 'G-FESZEYLND9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUb7zT10_GfMqvocrlw_yk5n8Dgk7I770',
    appId: '1:428608858205:android:da627c1bfa2fc9fd8445b4',
    messagingSenderId: '428608858205',
    projectId: 'govt-billing-app',
    storageBucket: 'govt-billing-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpoHUM_Ma5lHrhkP_s-Ip6W6d8YYwoYNQ',
    appId: '1:428608858205:ios:4b4f73e80983b8398445b4',
    messagingSenderId: '428608858205',
    projectId: 'govt-billing-app',
    storageBucket: 'govt-billing-app.appspot.com',
    iosBundleId: 'com.example.govtBilling',
  );
}
